apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: update-driver-status
  name: update-driver-status
  namespace: default
spec:
  selector:
    matchLabels:
      app: update-driver-status
  replicas: 1
  template:
    metadata:
      labels:
        app: update-driver-status
    spec:
      containers:
      - image: gcr.io/update-driver-status-image:latest
        name: update-driver-status
        ports:
        - containerPort: 8080
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: update-driver-status
  namespace: default
  labels:
    service: update-driver-status
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: update-driver-status