apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: get-drivers
  name: get-drivers
  namespace: default
spec:
  selector:
    matchLabels:
      app: get-drivers
  replicas: 1
  template:
    metadata:
      labels:
        app: get-drivers
    spec:
      containers:
      - image: gcr.io/get-drivers-image:latest
        name: get-drivers
        ports:
        - containerPort: 8080
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: get-drivers
  namespace: default
  labels:
    service: get-drivers
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: get-drivers